apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ssh
  labels:
    app: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      serviceAccountName: k8s-admin
      containers:
      - name: ssh
        image: 730335256432.dkr.ecr.eu-west-1.amazonaws.com/bounce:latest
        ports:
        - containerPort: 22
        env:
        - name: DB_RDS
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rdsdns
        - name: USER_NAME
          value: "root"
        - name: USER_PASSWORD
          value: "password"
        - name: PASSWORD_ACCESS
          value: "true"
        - name: SUDO_ACCESS
          value: "true"   
